<a href="https://colab.research.google.com/github/ajrodriguezo/CodigoFacilito_CienciaDeDatos/blob/main/frecode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a+20

array([20, 21, 22, 23, 24])

In [ ]:
a


array([0, 1, 2, 3, 4])

In [ ]:
print(a<=3)

[ True  True  True  True False]


In [4]:
import pandas as pd

In [6]:
certificates_earned = pd.Series([8,2,5,6], index=['tom','kris','ahmad','beau'])

In [7]:
from math import ceil
print(certificates_earned[certificates_earned>5])

tom     8
beau    6
dtype: int64


In [8]:
certificates_earned = pd.DataFrame({'certificares':[8,2,5,6],'time(in months)':[16,5,9,12]})

In [9]:
certificates_earned.index = ['Tom','Kris','ahmad','Beau']

In [10]:
print(certificates_earned.iloc[2])

certificares       5
time(in months)    9
Name: ahmad, dtype: int64


In [11]:
certificates_earned = pd.DataFrame({
    'Cerficates':[8,2,5,6],
    'Time(in months)':[16,5,9,12]
})

names =['Tom','Kris','Ahmad','Beau']


In [12]:
certificates_earned.index = names
longest_streak = pd.Series([13,11,9,7], index=names)
certificates_earned['longest streak']= longest_streak

In [13]:
print(certificates_earned)

       Cerficates  Time(in months)  longest streak
Tom             8               16              13
Kris            2                5              11
Ahmad           5                9               9
Beau            6               12               7


In [16]:
certificates_earned['Cerficates per month']=round(certificates_earned['Cerficates']/certificates_earned['Time(in months)'],2)

In [17]:
certificates_earned

Cerficates  Time(in months)  longest streak  Cerficates per month
Tom             8               16              13                  0.50
Kris            2                5              11                  0.40
Ahmad           5                9               9                  0.56
Beau            6               12               7                  0.50